# Generated by Django 2.0.4 on 2018-04-23 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(editable=False, max_length=30, unique=True),
        ),
    ]
