# Generated by Django 2.0.4 on 2018-04-24 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20180423_2319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='friends',
            new_name='friendships',
        ),
    ]
