# Generated by Django 2.0.4 on 2018-04-30 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_auto_20180424_2240'),
        ('authentication', '0006_auto_20180427_1617'),
    ]

    operations = [
    ]
