# Generated by Django 2.0.4 on 2018-05-01 14:06

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theaters', '0005_auto_20180427_1617'),
        ('authentication', '0007_merge_20180430_1910'),
    ]

    operations = [
        migrations.CreateModel(
            name='FanZoneAdmin',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('theater', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fanzoneadmins', to='theaters.Theater')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('authentication.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='theateradmin',
            name='theater',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='theateradmins', to='theaters.Theater'),
        ),
    ]
