# Generated by Django 2.0.4 on 2018-05-08 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media_upload', '0004_auto_20180508_2255'),
        ('authentication', '0008_auto_20180501_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media_upload.Image'),
        ),
    ]
