# Generated by Django 2.0.5 on 2018-05-23 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_login',
        ),
        migrations.AddField(
            model_name='user',
            name='single_use_token',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
