# Generated by Django 2.0.4 on 2018-05-04 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0005_auto_20180503_1936'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketOnSale',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('auditorium', models.CharField(max_length=255)),
                ('seat', models.IntegerField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('discount', models.IntegerField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets_on_sale', to='movies.Movie')),
            ],
        ),
    ]
