# Generated by Django 2.0.5 on 2018-05-07 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('showtimes', '0002_showtime_movie'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sale_tickets', '0003_ticketonsale_theater'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('discount', models.IntegerField(default=0)),
                ('seat', models.IntegerField()),
                ('showtime', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='showtimes.Showtime')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
