# Generated by Django 2.0.4 on 2018-05-23 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale_tickets', '0006_auto_20180522_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketonsale',
            name='deleted',
            field=models.IntegerField(default=0),
        ),
    ]
