# Generated by Django 2.0.4 on 2018-04-24 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theaters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='theater',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=5, max_digits=2),
            preserve_default=False,
        ),
    ]
