# Generated by Django 2.0.4 on 2018-04-24 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theaters', '0002_theater_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='theater',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
