# Generated by Django 2.0.4 on 2018-04-27 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theaters', '0003_theater_votes'),
        ('theaters', '0002_remove_theater_admin'),
    ]

    operations = [
    ]
