# Generated by Django 2.0.4 on 2018-04-27 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('theaters', '0004_merge_20180427_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='theater',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='theater',
            name='votes',
        ),
        migrations.AddField(
            model_name='theater',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='voting',
            name='theater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='theaters.Theater'),
        ),
        migrations.AddField(
            model_name='voting',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='theater',
            name='voters',
            field=models.ManyToManyField(related_name='voters', through='theaters.Voting', to=settings.AUTH_USER_MODEL),
        ),
    ]
