# Generated by Django 2.0.4 on 2018-04-27 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theaters', '0004_auto_20180424_1523'),
        ('theaters', '0002_remove_theater_admin'),
    ]

    operations = [
    ]
