# Generated by Django 2.0.4 on 2018-05-08 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media_upload', '0002_auto_20180508_1550'),
        ('theaters', '0005_auto_20180427_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='theater',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media_upload.Image'),
        ),
    ]
