# Generated by Django 2.0.5 on 2018-05-23 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theaters', '0006_theater_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='theater',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='theater',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=20, null=True),
        ),
    ]
