# Generated by Django 2.0.5 on 2018-05-12 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theaters', '0006_theater_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditorium',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('layout', models.TextField()),
                ('theater', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditoriums', to='theaters.Theater')),
            ],
        ),
    ]
