# Generated by Django 2.0.5 on 2018-05-27 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theaters', '0007_auditorium'),
        ('theaters', '0007_auto_20180523_0947'),
    ]

    operations = [
    ]
