# Generated by Django 2.0.4 on 2018-04-28 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theaters', '0005_auto_20180427_1617'),
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='theater',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='theaters.Theater'),
        ),
    ]
