# Generated by Django 2.0.4 on 2018-05-08 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media_upload', '0003_auto_20180508_1649'),
        ('movies', '0005_auto_20180503_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media_upload.Image'),
        ),
    ]
