# Generated by Django 2.0.4 on 2018-04-23 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20180423_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='admin',
        ),
    ]
