# Generated by Django 2.0.4 on 2018-04-23 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_auto_20180423_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='admin',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
