# Generated by Django 2.0.4 on 2018-04-23 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_auto_20180423_1558'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='admin',
            new_name='admin_id',
        ),
    ]
