# Generated by Django 2.0.4 on 2018-04-23 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_auto_20180423_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='admin_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
