# Generated by Django 2.0.4 on 2018-04-23 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0013_auto_20180423_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='admin_id',
        ),
        migrations.AddField(
            model_name='movie',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
