# Generated by Django 2.0.4 on 2018-05-02 07:47

from django.db import migrations

from reservations.models import BASIC
from reservations.models import BRONZE
from reservations.models import SILVER
from reservations.models import GOLD


def populate_table(apps, schema_editor):

    RewardScale = apps.get_model('reservations', 'RewardScale')

    reward = {
        'status': BASIC[0],
        'min_points': 0,
        'max_points': 24
    }

    RewardScale.objects.create(**reward)

    reward['status'] = BRONZE[0]
    reward['min_points'] = 25
    reward['max_points'] = 49

    RewardScale.objects.create(**reward)

    reward['status'] = SILVER[0]
    reward['min_points'] = 50
    reward['max_points'] = 74

    RewardScale.objects.create(**reward)

    reward['status'] = GOLD[0]
    reward['min_points'] = 75
    reward['max_points'] = 100

    RewardScale.objects.create(**reward)


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_table)
    ]
