# Generated by Django 2.0.4 on 2018-04-30 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media_upload', '0001_initial'),
        ('theaters', '0005_auto_20180427_1617'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('supercategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='fan_zone.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Prop',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='OfficialProp',
            fields=[
                ('prop_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fan_zone.Prop')),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('theater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='officialprops', to='theaters.Theater')),
            ],
            bases=('fan_zone.prop',),
        ),
        migrations.AddField(
            model_name='prop',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='officialprops', to='fan_zone.Category'),
        ),
        migrations.AddField(
            model_name='prop',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media_upload.Image'),
        ),
    ]
