# Generated by Django 2.0.4 on 2018-05-07 08:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media_upload', '0002_auto_20180507_0859'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('theaters', '0005_auto_20180427_1617'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('supercategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='fan_zone.Category')),
            ],
        ),
        migrations.CreateModel(
            name='OfficialProp',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='officialprops', to='fan_zone.Category')),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media_upload.Image')),
                ('theater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='officialprops', to='theaters.Theater')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UsedProp',
            fields=[
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('version', models.IntegerField()),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('post_date', models.DateField(auto_now_add=True)),
                ('expiration_date', models.DateField()),
                ('approved', models.BooleanField(default=False)),
                ('pending_approval', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usedprops', to='fan_zone.Category')),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media_upload.Image')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usedprops', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
