# Generated by Django 2.0.5 on 2018-05-08 17:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fan_zone', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='officialprop',
            name='post_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usedprop',
            name='version',
            field=models.IntegerField(default=1),
        ),
    ]
