# Generated by Django 2.0.4 on 2018-05-03 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fan_zone', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prop',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
