# Generated by Django 2.0.5 on 2018-05-13 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fan_zone', '0002_auto_20180508_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officialprop',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='fan_zone.Category'),
        ),
        migrations.AlterField(
            model_name='usedprop',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='fan_zone.Category'),
        ),
    ]
