# Generated by Django 2.0.5 on 2018-05-14 10:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('theaters', '0006_theater_image'),
        ('media_upload', '0005_auto_20180509_0841'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fan_zone', '0003_auto_20180513_0827'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prop',
            fields=[
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('post_date', models.DateField(auto_now_add=True)),
                ('quantity', models.IntegerField(null=True)),
                ('price', models.FloatField(null=True)),
                ('expiration_date', models.DateField(null=True)),
                ('approved', models.BooleanField(default=False)),
                ('pending_approval', models.BooleanField(default=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('O', 'Official'), ('U', 'Used')], max_length=1)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='fan_zone.Category')),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media_upload.Image')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('theater', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='theaters.Theater')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('official', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='officialprop',
            name='category',
        ),
        migrations.RemoveField(
            model_name='officialprop',
            name='image',
        ),
        migrations.RemoveField(
            model_name='officialprop',
            name='theater',
        ),
        migrations.RemoveField(
            model_name='usedprop',
            name='category',
        ),
        migrations.RemoveField(
            model_name='usedprop',
            name='image',
        ),
        migrations.RemoveField(
            model_name='usedprop',
            name='owner',
        ),
        migrations.DeleteModel(
            name='OfficialProp',
        ),
        migrations.DeleteModel(
            name='UsedProp',
        ),
    ]
