# Generated by Django 2.0.5 on 2018-05-23 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fan_zone', '0007_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='amount',
            field=models.FloatField(),
        ),
    ]
