# Generated by Django 2.0.4 on 2018-04-29 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Showtime',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('auditorium', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=6)),
            ],
        ),
    ]
