# Generated by Django 2.0.4 on 2018-04-29 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20180429_1811'),
        ('showtimes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='showtime',
            name='movie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='showtimes', to='movies.Movie'),
        ),
    ]
