# Generated by Django 2.0.5 on 2018-05-13 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        # this might cause problems later
        ('theaters', '__latest__'),
        ('showtimes', '0002_showtime_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showtime',
            name='auditorium',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='arst', to='theaters.Auditorium'),
        ),
    ]
