# Generated by Django 2.0.4 on 2018-04-28 14:23

from django.db import migrations, models
import media_upload.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('o', 'Official Prop Image')], max_length=1)),
                ('data', models.ImageField(upload_to=media_upload.models.generate_image_path)),
            ],
        ),
    ]
