# Generated by Django 2.0.4 on 2018-05-07 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='kind',
            field=models.CharField(choices=[('o', 'Official Prop Image'), ('u', 'Official Prop Image')], max_length=1),
        ),
    ]
