# Generated by Django 2.0.4 on 2018-05-08 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_upload', '0002_auto_20180508_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='kind',
            field=models.CharField(choices=[('o', 'Official Prop Image'), ('t', 'Theater Image'), ('m', 'Movie Image')], max_length=1),
        ),
    ]
