# Generated by Django 2.0.5 on 2018-05-09 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_upload', '0004_auto_20180508_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='kind',
            field=models.CharField(choices=[('o', 'Official Prop Image'), ('z', 'Used Prop Image'), ('t', 'Theater Image'), ('m', 'Movie Image'), ('u', 'User Image')], max_length=1),
        ),
    ]
